#!/bin/bash

nvim_config_dir=$HOME/.config/nvim
ghostty_config_dir=$HOME/.config/ghostty
zshrc_config_file=$HOME/.zshrc
tmux_config_file=$HOME/.tmux.conf
nvim_old_config_dir=$HOME/.config/nvim-old
ghostty_old_config_dir=$HOME/.config/ghostty-old

if [[ $* == *--uninstall* ]]
then
    unlink $nvim_config_dir
    exit 0
fi

if [[ -L "$nvim_config_dir" ]]
then
	rm $nvim_config_dir
elif [[ -d "$nvim_config_dir" ]]
then
	mv $nvim_config_dir $nvim_old_config_dir
fi

if [[ -L "$ghostty_config_dir" ]]
then
	rm $ghostty_config_dir
elif [[ -d "$ghostty_config_dir" ]]
then
	mv $ghostty_config_dir $ghostty_old_config_dir
fi

ln -s $PWD/nvim/.config/nvim $nvim_config_dir
ln -s $PWD/ghostty/.config/ghostty $ghostty_config_dir
ln -nsf $PWD/.zshrc $zshrc_config_file
ln -nsf $PWD/.tmux.conf $tmux_config_file
ln -nsf $PWD/zsh/functions $HOME/.config/zsh-functions
